/// Credit-scoring domain layer — pure models and the engine interface.
///
/// IMPLEMENTATION STATUS: RuleBasedCreditScoringEngine is IMPLEMENTED (rule-based,
/// deterministic). It is NOT a machine-learning model. The UI must not describe
/// it as AI/ML anywhere (docs/AGENTS.MD, docs/DATA_MODEL.md §3.11).
///
/// The interface allows a future validated engine to replace the demo
/// implementation without touching presentation code (docs/ARCHITECTURE.md §4).
library;

import 'package:flutter/foundation.dart';

import '../../../core/l10n/l10n.dart';

// ---------------------------------------------------------------------------
// Enums (docs/DATA_MODEL.md §2)
// ---------------------------------------------------------------------------

/// The four scoring categories (doc field: CreditCategory).
enum CreditCategory {
  energyUsage,
  paymentHistory,
  businessActivity,
  communityParticipation,
}

/// Score band — do NOT expose raw enum name in the UI; use [CreditBand.label].
///
/// Thresholds (docs/DATA_MODEL.md §4.1):
/// < 50 → perluPeningkatan, 50–64 → cukup, 65–79 → baik, 80–100 → baikSekali.
enum CreditBand {
  perluPeningkatan,
  cukup,
  baik,
  baikSekali;

  /// Indonesian display label.
  String get label => switch (this) {
    CreditBand.perluPeningkatan => 'Perlu Peningkatan',
    CreditBand.cukup => 'Cukup',
    CreditBand.baik => 'Baik',
    CreditBand.baikSekali => 'Baik Sekali',
  };

  String localizedLabel(AppLocalizations l10n) => switch (this) {
    CreditBand.perluPeningkatan => l10n.creditBandPerluPeningkatan,
    CreditBand.cukup => l10n.creditBandCukup,
    CreditBand.baik => l10n.creditBandBaik,
    CreditBand.baikSekali => l10n.creditBandBaikSekali,
  };
}

/// Whether a factor is contributing positively, negatively, or neutrally.
///
/// Direction rule (docs/DATA_MODEL.md §3.11):
/// ratio ≥ 0.6 → positive, 0.4–0.6 → neutral, < 0.4 → negative.
enum FactorDirection { positive, negative, neutral }

// ---------------------------------------------------------------------------
// Value objects
// ---------------------------------------------------------------------------

/// Raw normalised inputs (0.0–1.0) seeded from the demo scenario.
/// The engine derives integer category scores from these.
/// docs/DATA_MODEL.md §3.11.
@immutable
class CreditScoreInputs {
  const CreditScoreInputs({
    required this.energyUsageConsistency,
    required this.paymentHistory,
    required this.businessActivity,
    required this.communityParticipation,
  });

  /// Consistency of energy usage — maps to [CreditCategory.energyUsage], max 35.
  final double energyUsageConsistency;

  /// Payment history — maps to [CreditCategory.paymentHistory], max 30.
  final double paymentHistory;

  /// Business activity — maps to [CreditCategory.businessActivity], max 20.
  final double businessActivity;

  /// Community participation — maps to [CreditCategory.communityParticipation], max 15.
  final double communityParticipation;

  /// Convenience: Ibu Clara canonical seed (docs/DATA_MODEL.md §4.1).
  static const CreditScoreInputs claraDemo = CreditScoreInputs(
    energyUsageConsistency: 0.857,
    paymentHistory: 0.80,
    businessActivity: 0.90,
    communityParticipation: 0.667,
  );
}

/// One explainable factor per category, generated by the engine.
/// docs/DATA_MODEL.md §3.11.
@immutable
class CreditFactor {
  const CreditFactor({
    required this.category,
    required this.label,
    required this.direction,
    required this.points,
    required this.maxPoints,
    required this.reason,
  });

  final CreditCategory category;

  /// Indonesian display label (e.g. \"Konsistensi pemakaian energi\").
  final String label;

  final FactorDirection direction;

  /// Computed integer points for this category.
  final int points;

  /// Maximum possible points for this category.
  final int maxPoints;

  /// Plain one-sentence reason, generated from a per-category template.
  final String reason;
}

/// The complete computed credit score with its supporting factors.
/// CreditScore is ALWAYS derived by the engine — never seeded directly.
/// docs/DATA_MODEL.md §3.11.
@immutable
class CreditScore {
  const CreditScore({
    required this.score,
    required this.band,
    required this.factors,
    required this.eligibilityLabel,
    required this.computedAt,
  });

  /// Total score, 0–100. Equals the sum of all [factors] points.
  final int score;

  final CreditBand band;

  /// One [CreditFactor] per [CreditCategory]; order matches [CreditCategory].
  final List<CreditFactor> factors;

  /// Short eligibility message (e.g. \"Layak untuk melihat simulasi pembiayaan\").
  /// Does NOT include rupiah figures — those belong to the financing domain.
  final String eligibilityLabel;

  final DateTime computedAt;
}

// ---------------------------------------------------------------------------
// Engine interface
// ---------------------------------------------------------------------------

/// Pure interface for the credit-scoring engine.
///
/// The demo implementation is [RuleBasedCreditScoringEngine] (deterministic,
/// rule-based). A future production implementation can replace it here without
/// touching any UI code. See docs/ARCHITECTURE.md §4.
abstract interface class CreditScoringEngine {
  /// Compute a [CreditScore] from the given [inputs].
  ///
  /// This is a pure function — the same inputs always produce the same output.
  CreditScore compute(CreditScoreInputs inputs);
}
