/// The user's own records — the single source of truth for the app.
///
/// Everything here is entered or generated by the person using the app and is
/// persisted to their device. Nothing is bundled or invented: if a value has
/// never been recorded, the app shows an empty state rather than a placeholder.
///
/// Every model is immutable and round-trips through JSON so the whole document
/// can be written atomically (see `core/data/app_store.dart`).
library;

import 'package:flutter/foundation.dart';

// ---------------------------------------------------------------------------
// Profile
// ---------------------------------------------------------------------------

@immutable
class UserProfile {
  const UserProfile({
    required this.name,
    required this.businessName,
    required this.city,
    this.phone = '',
    required this.joinedAt,
    this.tariffIdrPerKwh = 1444.70,
  });

  final String name;
  final String businessName;
  final String city;
  final String phone;
  final DateTime joinedAt;

  /// The user's PLN tariff. Defaults to the common R-1/1300 VA rate but the
  /// user can correct it — every rupiah figure in the app derives from this.
  final double tariffIdrPerKwh;

  /// First name, for greetings.
  String get greetingName {
    final parts = name.trim().split(RegExp(r'\s+'));
    if (parts.length <= 2) return name.trim();
    return parts.take(2).join(' ');
  }

  UserProfile copyWith({
    String? name,
    String? businessName,
    String? city,
    String? phone,
    double? tariffIdrPerKwh,
  }) => UserProfile(
    name: name ?? this.name,
    businessName: businessName ?? this.businessName,
    city: city ?? this.city,
    phone: phone ?? this.phone,
    joinedAt: joinedAt,
    tariffIdrPerKwh: tariffIdrPerKwh ?? this.tariffIdrPerKwh,
  );

  Map<String, dynamic> toJson() => {
    'name': name,
    'businessName': businessName,
    'city': city,
    'phone': phone,
    'joinedAt': joinedAt.toIso8601String(),
    'tariffIdrPerKwh': tariffIdrPerKwh,
  };

  factory UserProfile.fromJson(Map<String, dynamic> j) => UserProfile(
    name: j['name'] as String? ?? '',
    businessName: j['businessName'] as String? ?? '',
    city: j['city'] as String? ?? '',
    phone: j['phone'] as String? ?? '',
    joinedAt:
        DateTime.tryParse(j['joinedAt'] as String? ?? '') ?? DateTime.now(),
    tariffIdrPerKwh: (j['tariffIdrPerKwh'] as num?)?.toDouble() ?? 1444.70,
  );
}

// ---------------------------------------------------------------------------
// Electricity bill
// ---------------------------------------------------------------------------

/// One monthly PLN bill the user recorded.
@immutable
class Bill {
  const Bill({
    required this.id,
    required this.periodMonth,
    required this.kwh,
    required this.totalIdr,
    this.photoPath,
    required this.recordedAt,
  });

  final String id;

  /// First day of the billing month.
  final DateTime periodMonth;
  final double kwh;
  final int totalIdr;

  /// Optional local path to a photo of the bill.
  final String? photoPath;
  final DateTime recordedAt;

  /// Effective rate this bill was charged at.
  double get idrPerKwh => kwh <= 0 ? 0 : totalIdr / kwh;

  Map<String, dynamic> toJson() => {
    'id': id,
    'periodMonth': periodMonth.toIso8601String(),
    'kwh': kwh,
    'totalIdr': totalIdr,
    'photoPath': photoPath,
    'recordedAt': recordedAt.toIso8601String(),
  };

  factory Bill.fromJson(Map<String, dynamic> j) => Bill(
    id: j['id'] as String,
    periodMonth: DateTime.parse(j['periodMonth'] as String),
    kwh: (j['kwh'] as num).toDouble(),
    totalIdr: (j['totalIdr'] as num).toInt(),
    photoPath: j['photoPath'] as String?,
    recordedAt:
        DateTime.tryParse(j['recordedAt'] as String? ?? '') ?? DateTime.now(),
  );
}

// ---------------------------------------------------------------------------
// Appliance inventory
// ---------------------------------------------------------------------------

/// A productive appliance the user declared, with the numbers needed to
/// attribute cost to it. Attribution is arithmetic on these declared values —
/// not a guess, and not a model.
@immutable
class Appliance {
  const Appliance({
    required this.id,
    required this.name,
    required this.watts,
    required this.hoursPerDay,
    required this.daysPerWeek,
    this.kind = 'other',
  });

  final String id;
  final String name;

  /// Rated power draw.
  final double watts;
  final double hoursPerDay;
  final int daysPerWeek;

  /// 'oven' | 'sewingMachine' | 'refrigerator' | 'blender' | 'other'.
  final String kind;

  /// Energy this appliance uses in a 30-day month, from the declared usage.
  double get monthlyKwh => watts / 1000 * hoursPerDay * daysPerWeek * (30 / 7);

  int monthlyCostIdr(double tariff) => (monthlyKwh * tariff).round();

  Appliance copyWith({
    String? name,
    double? watts,
    double? hoursPerDay,
    int? daysPerWeek,
    String? kind,
  }) => Appliance(
    id: id,
    name: name ?? this.name,
    watts: watts ?? this.watts,
    hoursPerDay: hoursPerDay ?? this.hoursPerDay,
    daysPerWeek: daysPerWeek ?? this.daysPerWeek,
    kind: kind ?? this.kind,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'watts': watts,
    'hoursPerDay': hoursPerDay,
    'daysPerWeek': daysPerWeek,
    'kind': kind,
  };

  factory Appliance.fromJson(Map<String, dynamic> j) => Appliance(
    id: j['id'] as String,
    name: j['name'] as String,
    watts: (j['watts'] as num).toDouble(),
    hoursPerDay: (j['hoursPerDay'] as num).toDouble(),
    daysPerWeek: (j['daysPerWeek'] as num).toInt(),
    kind: j['kind'] as String? ?? 'other',
  );
}

// ---------------------------------------------------------------------------
// Solar Hub session log
// ---------------------------------------------------------------------------

/// A session the user ran (or booked) on the shared solar hub.
@immutable
class SolarSession {
  const SolarSession({
    required this.id,
    required this.applianceName,
    required this.date,
    required this.slotLabel,
    required this.kwh,
    required this.recordedAt,
  });

  final String id;
  final String applianceName;
  final DateTime date;
  final String slotLabel;

  /// Energy drawn from the hub instead of the grid — this is what "saving"
  /// and "CO2 avoided" are computed from.
  final double kwh;
  final DateTime recordedAt;

  Map<String, dynamic> toJson() => {
    'id': id,
    'applianceName': applianceName,
    'date': date.toIso8601String(),
    'slotLabel': slotLabel,
    'kwh': kwh,
    'recordedAt': recordedAt.toIso8601String(),
  };

  factory SolarSession.fromJson(Map<String, dynamic> j) => SolarSession(
    id: j['id'] as String,
    applianceName: j['applianceName'] as String,
    date: DateTime.parse(j['date'] as String),
    slotLabel: j['slotLabel'] as String,
    kwh: (j['kwh'] as num).toDouble(),
    recordedAt:
        DateTime.tryParse(j['recordedAt'] as String? ?? '') ?? DateTime.now(),
  );
}

// ---------------------------------------------------------------------------
// Arisan
// ---------------------------------------------------------------------------

@immutable
class ArisanMember {
  const ArisanMember({required this.id, required this.name, this.isMe = false});

  final String id;
  final String name;
  final bool isMe;

  Map<String, dynamic> toJson() => {'id': id, 'name': name, 'isMe': isMe};

  factory ArisanMember.fromJson(Map<String, dynamic> j) => ArisanMember(
    id: j['id'] as String,
    name: j['name'] as String,
    isMe: j['isMe'] as bool? ?? false,
  );
}

/// The user's arisan circle, as they set it up.
@immutable
class ArisanGroup {
  const ArisanGroup({
    required this.name,
    required this.contributionIdr,
    required this.members,
    required this.startedAt,
  });

  final String name;

  /// Agreed monthly contribution per member.
  final int contributionIdr;
  final List<ArisanMember> members;
  final DateTime startedAt;

  int get potIdr => contributionIdr * members.length;

  ArisanGroup copyWith({
    String? name,
    int? contributionIdr,
    List<ArisanMember>? members,
  }) => ArisanGroup(
    name: name ?? this.name,
    contributionIdr: contributionIdr ?? this.contributionIdr,
    members: members ?? this.members,
    startedAt: startedAt,
  );

  Map<String, dynamic> toJson() => {
    'name': name,
    'contributionIdr': contributionIdr,
    'members': members.map((m) => m.toJson()).toList(),
    'startedAt': startedAt.toIso8601String(),
  };

  factory ArisanGroup.fromJson(Map<String, dynamic> j) => ArisanGroup(
    name: j['name'] as String,
    contributionIdr: (j['contributionIdr'] as num).toInt(),
    members: (j['members'] as List)
        .map((e) => ArisanMember.fromJson(e as Map<String, dynamic>))
        .toList(),
    startedAt:
        DateTime.tryParse(j['startedAt'] as String? ?? '') ?? DateTime.now(),
  );
}

/// An append-only entry in the group's transparent record.
@immutable
class LedgerEntry {
  const LedgerEntry({
    required this.id,
    required this.type,
    required this.memberId,
    required this.memberName,
    this.amountIdr,
    this.amountKwh,
    required this.at,
    this.note,
  });

  final String id;

  /// 'contribution' | 'payout' | 'quotaShared' | 'quotaReceived'.
  final String type;
  final String memberId;
  final String memberName;
  final int? amountIdr;
  final double? amountKwh;
  final DateTime at;
  final String? note;

  Map<String, dynamic> toJson() => {
    'id': id,
    'type': type,
    'memberId': memberId,
    'memberName': memberName,
    'amountIdr': amountIdr,
    'amountKwh': amountKwh,
    'at': at.toIso8601String(),
    'note': note,
  };

  factory LedgerEntry.fromJson(Map<String, dynamic> j) => LedgerEntry(
    id: j['id'] as String,
    type: j['type'] as String,
    memberId: j['memberId'] as String,
    memberName: j['memberName'] as String,
    amountIdr: (j['amountIdr'] as num?)?.toInt(),
    amountKwh: (j['amountKwh'] as num?)?.toDouble(),
    at: DateTime.parse(j['at'] as String),
    note: j['note'] as String?,
  );
}

// ---------------------------------------------------------------------------
// Energy quota sharing (a record of an agreement, not an energy transfer)
// ---------------------------------------------------------------------------

@immutable
class QuotaOffer {
  const QuotaOffer({
    required this.id,
    required this.ownerId,
    required this.ownerName,
    required this.amountKwh,
    required this.slotLabel,
    this.note,
    required this.status,
    required this.createdAt,
    this.takenByName,
  });

  final String id;
  final String ownerId;
  final String ownerName;
  final double amountKwh;
  final String slotLabel;
  final String? note;

  /// 'open' | 'taken' | 'cancelled'.
  final String status;
  final DateTime createdAt;
  final String? takenByName;

  QuotaOffer copyWith({String? status, String? takenByName}) => QuotaOffer(
    id: id,
    ownerId: ownerId,
    ownerName: ownerName,
    amountKwh: amountKwh,
    slotLabel: slotLabel,
    note: note,
    status: status ?? this.status,
    createdAt: createdAt,
    takenByName: takenByName ?? this.takenByName,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'ownerId': ownerId,
    'ownerName': ownerName,
    'amountKwh': amountKwh,
    'slotLabel': slotLabel,
    'note': note,
    'status': status,
    'createdAt': createdAt.toIso8601String(),
    'takenByName': takenByName,
  };

  factory QuotaOffer.fromJson(Map<String, dynamic> j) => QuotaOffer(
    id: j['id'] as String,
    ownerId: j['ownerId'] as String,
    ownerName: j['ownerName'] as String,
    amountKwh: (j['amountKwh'] as num).toDouble(),
    slotLabel: j['slotLabel'] as String,
    note: j['note'] as String?,
    status: j['status'] as String,
    createdAt: DateTime.parse(j['createdAt'] as String),
    takenByName: j['takenByName'] as String?,
  );
}

// ---------------------------------------------------------------------------
// Saved financing calculation
// ---------------------------------------------------------------------------

/// A calculation the user chose to keep, so they can compare plans later.
@immutable
class SavedCalculation {
  const SavedCalculation({
    required this.id,
    required this.label,
    required this.principalIdr,
    required this.tenorMonths,
    required this.monthlyRatePct,
    required this.savedAt,
  });

  final String id;
  final String label;
  final int principalIdr;
  final int tenorMonths;
  final double monthlyRatePct;
  final DateTime savedAt;

  int get totalCostIdr =>
      (principalIdr * (monthlyRatePct / 100) * tenorMonths).round();
  int get totalRepaymentIdr => principalIdr + totalCostIdr;
  int get monthlyInstallmentIdr => (totalRepaymentIdr / tenorMonths).round();

  Map<String, dynamic> toJson() => {
    'id': id,
    'label': label,
    'principalIdr': principalIdr,
    'tenorMonths': tenorMonths,
    'monthlyRatePct': monthlyRatePct,
    'savedAt': savedAt.toIso8601String(),
  };

  factory SavedCalculation.fromJson(Map<String, dynamic> j) => SavedCalculation(
    id: j['id'] as String,
    label: j['label'] as String,
    principalIdr: (j['principalIdr'] as num).toInt(),
    tenorMonths: (j['tenorMonths'] as num).toInt(),
    monthlyRatePct: (j['monthlyRatePct'] as num).toDouble(),
    savedAt: DateTime.parse(j['savedAt'] as String),
  );
}
